version: "3"

services:
  frontend-qat:
    container_name: frontend-qat
    image: amonte13/eshop:front1-qat
    environment:
      CLIENT_URL: http://backend-qat:3100
    ports:
      - "5100:4100"

  frontend-shop-qat:
    container_name: frontend-shop-qat
    image: amonte13/eshop:front2-qat
    environment:
      CLIENT_URL: http://backend-qat:3100
    ports:
      - "5200:4200"